name: Run Selenium Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  selenium-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: pip #caching pip dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Selenium tests
      run: |
        pytest master_test_suite.py --headless --browser=chrome
